name: Trigger Netlify Build
on:
  schedule:
    - cron: '0 0 * * *' # daily
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/62009893f8236ba77a71eeb1
